### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by cevin** [wtolson/gnsq#21]
```
>>> import gnsq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cevin/a/venv/lib/python3.7/site-packages/gnsq/__init__.py", line 4, in <module>
    from .reader import Reader
  File "/Users/cevin/a/venv/lib/python3.7/site-packages/gnsq/reader.py", line 110
    async=False,
        ^
SyntaxError: invalid syntax
```

**Comment by wtolson** [comment]
Fixed in #24
